### ISSUE TITLE
sub_atom/5 bug

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#267]
While debugging failed tests for the Logtalk `lgtdoc` tool, I noticed a bug in the `sub_atom/5` predicate. Tracing it we get:

```text
 [0] EXIT trace
 [1] CALL sub_atom('/Users/pmoura/logtalk/tools/lgtunit/',_,1,0,/)
 [2] FAIL sub_atom('/Users/pmoura/logtalk/tools/lgtunit/',_,1,0,/)
```

But if we change the call from `sub_atom(Directory, _, 1, 0, '/')` to `sub_atom(Directory, _, _, 0, '/')` we get instead:

```text
 [0] EXIT trace
 [1] CALL sub_atom('/Users/pmoura/logtalk/tools/lgtunit/',_,_,0,/)
 [2] EXIT sub_atom('/Users/pmoura/logtalk/tools/lgtunit/',35,11,0,/)
```

Note that while the `35` value (for the *before* argument) is correct, the `11` value (for the *length* argument) is wrong (it should be `1`).

**Comment by pmoura** [comment]
Pushed additional tests for the `sub_atom/5` predicate but they don't trigger the bug above in the same way that trying the goals above at the top-level also don't trigger the bug:

```text
$ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.13.40
?- sub_atom('/Users/pmoura/logtalk/tools/lgtunit/',_,1,0,/).
true 
; false.
?- sub_atom('/Users/pmoura/logtalk/tools/lgtunit/',Before,Length,0,/).
Before = 35, Length = 1 
; ?- 
```

**Comment by pmoura** [comment]
Also, `sub_atom/5` calls where the *before* or *after* argument is bound should not leave a choice-point.

**Comment by infradig** [comment]
Yes, the code looks a bit strange and needs going over.

**Comment by infradig** [comment]
What?

     sub_atom(abcdef,1,Len,After,A).

must generate multiple choices.

**Comment by infradig** [comment]
You need 2 of before, len or after to get no choice-point.

**Comment by infradig** [comment]
This should not leave a choice-point:

**Comment by infradig** [comment]
This should not leave a choice-point:

  sub_atom('/Users/pmoura/logtalk/tools/lgtunit/',_,1,0,/)


but does for some reason I can't immediately see.

**Comment by pmoura** [comment]
Sorry, I meant when also the last argument is bound.

**Comment by pmoura** [comment]
I pushed determinism tests for the predicate. Currently, we get:

```text
$ logtalk_tester -p trealla -s /Users/pmoura/Documents/Logtalk/
% Batch testing started @ 2021-09-22 14:09:02
%         Logtalk version: 3.51.0-b01
%         Trealla Prolog version: 1.13.40
%
% logtalk3/tests/prolog/predicates/sub_atom_5
%         49 tests: 4 skipped, 43 passed, 2 failed (0 flaky)
%         completed tests from object tests in 1 second
%         clause coverage n/a
%
% Compilation errors/warnings and failed unit tests
% (compilation errors/warnings might be expected depending on the test)
!     lgt_sub_atom_5_45: failure (in 6.600000000012152e-05 seconds)
!       test goal succeeded non-deterministically
!       in file /Users/pmoura/Documents/Logtalk/logtalk3/tests/prolog/predicates/sub_atom_5/tests.lgt between lines 172-175
!     lgt_sub_atom_5_46: failure (in 2.699999999999925e-05 seconds)
!       test goal succeeded non-deterministically
!       in file /Users/pmoura/Documents/Logtalk/logtalk3/tests/prolog/predicates/sub_atom_5/tests.lgt between lines 175-178
%
% Skipped tests
logtalk3/tests/prolog/predicates/sub_atom_5/tests.lgt - sics_sub_atom_5_29 @ tests
logtalk3/tests/prolog/predicates/sub_atom_5/tests.lgt - sics_sub_atom_5_30 @ tests
logtalk3/tests/prolog/predicates/sub_atom_5/tests.lgt - sics_sub_atom_5_31 @ tests
logtalk3/tests/prolog/predicates/sub_atom_5/tests.lgt - sics_sub_atom_5_32 @ tests
%
% Failed tests
logtalk3/tests/prolog/predicates/sub_atom_5/tests.lgt - lgt_sub_atom_5_45 @ tests
logtalk3/tests/prolog/predicates/sub_atom_5/tests.lgt - lgt_sub_atom_5_46 @ tests
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timedout, 0 crashed
% 49 tests: 4 skipped, 43 passed, 2 failed (0 flaky)
%
% Batch testing ended @ 2021-09-22 14:09:04
```

The two failures are for the case you mention.

**Comment by infradig** [comment]
I think I fixed that.

**Comment by pmoura** [comment]
Indeed. I just pulled v1.13.40-4-g2e66a and all tests now pass. But I still get:

```text
 [0] EXIT trace
 [1] CALL sub_atom('/Users/pmoura/logtalk/tools/lgtunit/',_,_,0,/)
 [2] EXIT sub_atom('/Users/pmoura/logtalk/tools/lgtunit/',35,11,0,/)
```

I.e. `11` instead of `1`.

**Comment by infradig** [comment]
Ok, seems sub_atom/5 uses strlen (actually strlen_uft8) which measures the
underlying cstring (NULL-terminated) rather than taking account of the
slice (length). So that I think is where the extra length reported is
coming from. Should be an easy fix.

**Comment by pmoura** [comment]
The issue seems fixed in https://github.com/infradig/trealla/commit/93c242646bbc8a7839e1d412f7790360e754ef3d. I now get the correct length.
